# window variables
WINDOW_TITLE = "Level Editor"
FPS = 60
TILE_SIZE = 32
WINDOW_WIDTH = TILE_SIZE * 22
WINDOW_HEIGHT = TILE_SIZE * 18

MAIN_BG_COLOR = (131, 197, 247)

# variables for buttons
BUTTON_WIDTH, BUTTON_HEIGHT = 100, 40
BUTTON_MARGIN_LEFT = 12

# selection area variables
SELECTION_AREA_TILE_SIZE = 32
SELECTION_AREA_TILES_PER_ROW = 14
SELECTION_AREA_PADDING_LEFT = 36
SELECTION_AREA_PADDING_TOP = 18
SELECTION_AREA_GRID_GAP = 1
SELECTION_AREA_WIDTH = (SELECTION_AREA_TILE_SIZE + SELECTION_AREA_GRID_GAP) * SELECTION_AREA_TILES_PER_ROW + 2 * SELECTION_AREA_PADDING_LEFT
SELECTION_AREA_BGC = (80, 200, 50)
SELECTION_AREA_TOP_LEFT = WINDOW_WIDTH + SELECTION_AREA_PADDING_LEFT

TILEMAP_TILE_SIZE = 16

# variables for player
PLAYER_TILEMAP_SCALE = 2.5
PLAYER_ACTUAL_SCALE = 1.5

ENEMY_DIR = "assets/Enemy"
PLAYER_DIR = "assets/Player"
IDLE_ANIM = (1,2)

EMPTY = (0,0,0,0)

PORT_PADDING = 6